name: CI Pipeline Extended

on:
  pull_request:
  push:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 (linting)
        run: flake8 --max-line-length=100 app.py test_app.py

      - name: Run pytest (unit tests)
        run: pytest -v 

  # docker-build:
  #   runs-on: ubuntu-latest
  #   needs: lint-test
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build Docker image
  #       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-tp2-hello .

  #     - name: Push Docker image
  #       run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-tp2-hello